<template>
  <a
    href="https://www.songkick.com/artists/10191889"
    class="songkick-widget"
    data-theme="light"
    data-track-button="on"
    data-detect-style="on"
    data-locale="en"
    data-other-artists="on"
    data-share-button="on"
    data-country-filter="on"
    data-rsvp="on"
    data-request-show="on"
    data-past-events="off"
    data-past-events-offtour="off"
    data-remind-me="off"
    style="display: none"
  ></a>
</template>
