<template>
  <a
    href="https://www.songkick.com/artists/10191889"
    class="songkick-widget"
    data-theme="light"
    data-track-button="on"
    data-detect-style="off"
    data-background-color="rgb(255,255,255,1)"
    data-font-color="rgb(0,0,0,1)"
    data-button-bg-color="rgb(0,0,0,1)"
    data-button-text-color="rgb(255,255,255,1)"
    data-locale="en"
    data-other-artists="on"
    data-share-button="on"
    data-country-filter="on"
    data-rsvp="on"
    data-request-show="on"
    data-past-events="off"
    data-past-events-offtour="off"
    data-remind-me="off"
    style="display: none"
  ></a>
</template>
